{{- if .Values.pod.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.pod.pdb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.pod.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.pod.pdb.minAvailable }}
  minAvailable: {{ .Values.pod.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pod.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pod.pdb.maxUnavailable }}
  {{- end }}
{{- end }} 
