[env]
RUST_LOG={ value = "info, rocket::log::RocketLogger=warn", force = true }
RUST_BACKTRACE="1"

# Needed until http3 is stable
# However, given the limited use, and that the code has been baking
# since 2021, and its almost stable: https://github.com/seanmonstar/reqwest/issues/2303
# I'd like to give it a shot
[build]
rustflags = ["--cfg", "reqwest_unstable"]